import{a as S,i as y,S as q}from"./assets/vendor-Qob_5Ba8.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))e(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&e(l)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function e(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const E="46858966-ba511c0c272bf1bf47f1d2839",P="https://pixabay.com/api/";async function h(t,n=1){const s=new URLSearchParams({key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:n});try{return(await S.get(P,{params:s})).data}catch(e){throw console.error("Error fetching images:",e),e}}function m(t){return t.map(({webformatURL:n,largeImageURL:s,tags:e,likes:r=0,views:o=0,comments:l="",downloads:w=0})=>`
      <div class="galleries">
                <a href="${s}">
                    <img src="${n}" alt="${e}" />
                </a>
                <div class="content">
                    <div><p>Likes</p><span>${r}</span></div>
                    <div><p>Views</p><span>${o}</span></div>
                    <div><p>Comments</p><span>${l}</span></div>
                    <div><p>Downloads</p><span>${w}</span></div>
                </div>
            </div>
    `).join("")}function v(t){t.querySelectorAll(".galleries img").forEach(s=>{const e=s.parentElement.previousElementSibling;s.onload=()=>{e&&(e.style.display="none")},s.onerror=()=>{e&&(e.style.display="none")}})}const b=document.querySelector(".form"),a=document.querySelector(".gallery"),d=document.querySelector(".load-more"),i=document.querySelector(".loader");let f="",c=null,u=1,p=0,g=0;b.addEventListener("submit",M);d.addEventListener("click",$);async function M(t){t.preventDefault();const{textRow:n}=t.target.elements,s=n.value.trim();if(s===""){y.warning({title:"Caution",message:"The search field cannot be empty.",color:"red"});return}f=s,u=1,p=0,a.innerHTML="",d.style.display="none",i.style.display="block";try{const e=await h(f,u);i.style.display="none",e.hits.length===0?y.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!",color:"yellow"}):(g=e.totalHits,p=e.hits.length,a.innerHTML=m(e.hits),v(a),c?c.refresh():c=new q(".gallery .galleries a",{captionsData:"alt",captionDelay:250}),L())}catch(e){i.style.display="none",console.error("Error during image fetching:",e)}b.reset()}async function $(){u++,i.style.display="block";try{const t=await h(f,u);i.style.display="none",p+=t.hits.length,a.insertAdjacentHTML("beforeend",m(t.hits)),v(a),c&&c.refresh(),L(),H()}catch(t){i.style.display="none",console.error("Помилка при завантаженні додаткових зображень:",t)}}function L(){p>=g||g<15?(d.style.display="none",y.info({title:"Інформація",message:"Were sorry, but youve reached the end of search results."})):d.style.display="block"}function H(){const t=a.querySelector(".galleries");if(t){const{height:n}=t.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
