import{a as w,i as p,S}from"./assets/vendor-Qob_5Ba8.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))e(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&e(i)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function e(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const q="46858966-ba511c0c272bf1bf47f1d2839",E="https://pixabay.com/api/";async function g(t,n=1){const s=new URLSearchParams({key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:n});try{return(await w.get(E,{params:s})).data}catch(e){throw console.error("Error fetching images:",e),e}}function y(t){return t.map(({webformatURL:n,largeImageURL:s,tags:e,likes:r=0,views:o=0,comments:i="",downloads:b=0})=>`
      <div class="galleries">
                <a href="${s}">
                    <img src="${n}" alt="${e}" />
                </a>
                <div class="content">
                    <div><p>Likes</p><span>${r}</span></div>
                    <div><p>Views</p><span>${o}</span></div>
                    <div><p>Comments</p><span>${i}</span></div>
                    <div><p>Downloads</p><span>${b}</span></div>
                </div>
            </div>
    `).join("")}function m(t){t.querySelectorAll(".galleries img").forEach(s=>{const e=s.parentElement.previousElementSibling;s.onload=()=>{e&&(e.style.display="none")},s.onerror=()=>{e&&(e.style.display="none")}})}const h=document.querySelector(".form"),a=document.querySelector(".gallery"),c=document.querySelector(".load-more");document.querySelector(".loader");let f="",l=null,d=1,u=0,v=0;h.addEventListener("submit",P);c.addEventListener("click",M);async function P(t){t.preventDefault();const{textRow:n}=t.target.elements,s=n.value.trim();if(s===""){p.warning({title:"Caution",message:"The search field cannot be empty.",color:"red"});return}f=s,d=1,u=0,a.innerHTML="",c.style.display="none";try{const e=await g(f,d);e.hits.length===0?p.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!",color:"yellow"}):(v=e.totalHits,u=e.hits.length,a.innerHTML=y(e.hits),m(a),L(),l=l||new S(".gallery .galleries a",{captionsData:"alt",captionDelay:250}),l.refresh(),c.style.display="block")}catch(e){console.error("Error during image fetching:",e)}h.reset()}async function M(){d++;try{const t=await g(f,d);u+=t.hits.length,a.insertAdjacentHTML("beforeend",y(t.hits)),m(a),l&&l.refresh(),L(),$()}catch(t){console.error("Помилка при завантаженні додаткових зображень:",t)}}function L(){u>=v?(c.style.display="none",p.info({title:"Інформація",message:"Вибачте, але ви досягли кінця результатів пошуку."})):c.style.display="block"}function $(){const t=a.querySelector(".galleries");if(t){const{height:n}=t.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
